name: Docker Compose
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose build
        run: docker-compose build
      - name: test ostree
        run: docker run -it sjtug/flatpak-test:1.0
